spring:
  application:
    name: auth-service

  data:
    mongodb:
      # Injected from K8s Secret via env var
      uri: mongodb://admin:secret@localhost:27017/authDB?authSource=admin

  jackson:
    serialization:
      indent_output: true

  security:
    jwt:
      # Injected from K8s Secret via env var
      secret-key: 4748930e83a74df3ec63ab8cefc28684dc1ae4a74ecfe3f2343cee5543af2168
      token-duration: 1D

server:
  port: 7075

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info


