server:
  port: 8111

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - name: AuthenticationFilter

      routes:
        - id: supplier-route
          uri: lb://supplier-service
          predicates:
            - Path=/matchx/api/suppliers/**, /matchx/api/suppliers/v3/api-docs
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: supplierCircuitBreaker
                fallbackUri: forward:/fallback/suppliers

        - id: product-route
          uri: lb://product-service
          predicates:
            - Path=/matchx/api/products/**, /matchx/supplier/swagger-ui/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: productCircuitBreaker
                fallbackUri: forward:/fallback/products

        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/matchx/api/auth/**, /matchx/api/users/**
          filters:
            - StripPrefix=2

        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/matchx/api/orders/**, /matchx/api/orders/v3/api-docs
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/fallback/orders

        - id: order-matching-route
          uri: lb://order-matching-service
          predicates:
            - Path=/matchx/api/order-matching/**, /matchx/api/order-matching/v3/api-docs
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: orderMatchingCircuitBreaker
                fallbackUri: forward:/fallback/orderMatching

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Supplier Service
        url: /matchx/api/suppliers/v3/api-docs
      - name: Product Service
        url: /matchx/api/products/v3/api-docs
      - name: Order Service
        url: /matchx/api/orders/v3/api-docs
      - name: Order Matching Service
        url: /matchx/api/order-matching/v3/api-docs

resilience4j:
  circuitbreaker:
    instances:
      supplierCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

      productCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

      orderCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

      orderMatchingCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

security:
  jwt:
    secret-key: 4748930e83a74df3ec63ab8cefc28684dc1ae4a74ecfe3f2343cee5543af2168
    token-duration: 30m

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'


