spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/notification-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  devtools:
    restart:
      enabled: true

logging:
  level:
    com.capstone.scloud: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true


